export const projects = [
  {
    id:1,
    title: "Night Dream",
    description: "Night Dream is a mobile app that offers a wide range of wedding-related services — from venues and outfits to decorations and more. Users can easily browse and book services based on their location. The app also supports secure online payments and includes many other features waiting to be explored.",
    category: "Company Projects",
    features: "Multiple languages(En,Ar,De,Tr,Fa), Notifications, Payments(stripe), Auth (Google/Apple/Email)",
    mainImage: "/images/NightDream/main.png",
    arrayImage: [
      "/images/NightDream/q1.png",
      "/images/NightDream/q2.png",
      "/images/NightDream/q4.png",
      "/images/NightDream/q5.png",
      "/images/NightDream/q7.png",
      "/images/NightDream/q8.png",
      "/images/NightDream/q9.png",
    ],
    status: "In beta phase – APK available",
    github: "",
    downloadLink: "https://drive.google.com/file/d/1Ste32mD0_eZGYsk0Ye2gnwIgNM_FASzb/view?usp=drive_link",
    downloadLinkIOS: "https://drive.google.com/file/d/1hZDSCLfrof6izWUbhhreMZUroZY734DX/view?usp=drive_link",
    note:"",
  },
  {
    id:2,
    title: "Rehearsals",
    description: "AI Interview Coach is a Flutter-based web app that helps you practice real job interviews. The AI asks you tailored questions based on your field or specialty, then analyzes your answers to highlight your strengths and weaknesses. This helps you improve your performance and feel more confident in actual job interviews. Many more features are waiting to be explored — let’s discover them together!",
    category: "Company Projects",
    features: "Multi-language support (English, Arabic), Subscription-based payment system, Integrated payment gateways (Fatoorah), Interactive charts for interview analysis, JavaScript native code integration, Hardware testing (microphone/speaker readiness check), User authentication (Email)",
    mainImage: "/images/Rehearsals/main.png",
    arrayImage: [
      "/images/Rehearsals/1.jpg",
      "/images/Rehearsals/2.jpg",
      "/images/Rehearsals/3.jpg",
      "/images/Rehearsals/4.jpg",
      "/images/Rehearsals/5.jpg",
      "/images/Rehearsals/6.jpg",
    ],
    status: "Web version available",
    github: "",
    downloadLink: "",
    downloadLinkIOS:"",
    note:"The website is currently private and not publicly accessible due to the innovative nature of the idea and to respect privacy and confidentiality policies."
  },
  {
    id:3,
    title: "Qasaudna",
    description: "Qasaudna is a mobile app that lets you explore and listen to poems recited by your favorite poets. You can also search for songs and discover artistic content in one place. If you’re a poet yourself, you can join the platform and publish your own poems for others to enjoy. There’s so much more waiting for you — let’s explore it together!",
    category: "Personal Projects",
    features: "Multiple languages(En,Ar,De,Tr,Fa), Notifications, Payments(stripe), Auth (Google/Apple/Email)",
    mainImage: "/images/Qasaudna/q1.png",
    arrayImage: [
      "/images/Qasaudna/q1.png",
      "/images/Qasaudna/q2.png",
      "/images/Qasaudna/q3.png",
      "/images/Qasaudna/q4.png",
      "/images/Qasaudna/q5.png",
      "/images/Qasaudna/q6.png",
      "/images/Qasaudna/q7.png",
      "/images/Qasaudna/q8.png",
      "/images/Qasaudna/q9.png",
      "/images/Qasaudna/q10.png",
      "/images/Qasaudna/q11.png",
    ],
    status: "In beta phase – APK available",
    github: "",
    downloadLink: "",
    downloadLinkIOS:"",
    note:"",
  },
  {
    id:4,
    title: "Dentist App",
    description: "Dentist App is a mobile app that makes booking doctor appointments easy and convenient. Users can view the doctor's working hours and holidays, then schedule appointments accordingly with just a few taps. Doctors can manage all patient appointments, access medical inventory, and explore many more powerful features designed to simplify their workflow.",
    category: "Personal Projects",
    features: "Multiple languages(En,Ar,De,Tr,Fa), Notifications, Payments(stripe), Auth (Google/Apple/Email)",
    mainImage: "/images/DentistClinic/1.png",
    arrayImage: [
      "/images/DentistClinic/1.png",
      "/images/DentistClinic/2.png",
      "/images/DentistClinic/3.png",
      "/images/DentistClinic/4.png",
      "/images/DentistClinic/5.png",
      "/images/DentistClinic/6.png",
      "/images/DentistClinic/7.png",
      "/images/DentistClinic/8.png",
      "/images/DentistClinic/9.png",
      "/images/DentistClinic/11.png",
      "/images/DentistClinic/22.png",
      "/images/DentistClinic/33.png",
    ],
    status: "In beta phase – APK available",
    github: "",
    downloadLink: "",
    downloadLinkIOS:"",
    note:""
  },

    {
    id:5,
    title: "My Fatura",
    description: "My Fatura is a Flutter-based app that allows you to browse and purchase a wide range of makeup products available in your country. You can easily search for specific products, view availability by location, and even switch between different areas on the map to explore nearby stores and offerings. Many more features are waiting to be explored — let’s discover them together!.",
    category: "Company Projects",
    features: "google Maps -Mulite language (de,en) - Notifications",
    mainImage: "/images/Faturah/main.jpg",
    arrayImage: [
      "/images/Faturah/2.jpg",
      "/images/Faturah/3.jpg",
      "/images/Faturah/4.jpg",
      "/images/Faturah/5.jpg",
      "/images/Faturah/6.jpg",
      "/images/Faturah/7.jpg",
      "/images/Faturah/8.jpg",
      "/images/Faturah/9.jpg",
    ],
    status: "In beta phase – APK available",
    github: "",
    downloadLink: "",
    downloadLinkIOS:"",
    note:""
  },
];
